name: Docker build

on:
  workflow_dispatch:
  push:
    branches:
      - main

  # Build for any PRs.
  pull_request:

env:
  IMAGE_NAME: helloworld

jobs:
  # Build the container
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t testcontainers/helloworld:latest . --file Dockerfile

